# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pc\Desktop\gg\ans1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Stanley(object):
    def setupUi(self, Stanley):
        Stanley.setObjectName("Stanley")
        Stanley.resize(443, 177)
        Stanley.setMinimumSize(QtCore.QSize(443, 177))
        Stanley.setMaximumSize(QtCore.QSize(443, 177))
        Stanley.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.393323, y1:0.46, x2:0.911, y2:0.994318, stop:0.00995025 rgba(242, 255, 0, 255), stop:1 rgba(255, 121, 0, 255));")
        self.verticalLayout = QtWidgets.QVBoxLayout(Stanley)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(Stanley)
        self.listWidget.setStyleSheet("font: 63 14pt \"Cascadia Mono\";\n"
"background-color: qlineargradient(spread:pad, x1:0.482925, y1:0, x2:0.538, y2:1, stop:0.00995025 rgba(197, 221, 98, 255), stop:1 rgba(255, 157, 110, 255));")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)
        self.pushButton = QtWidgets.QPushButton(Stanley)
        self.pushButton.setMinimumSize(QtCore.QSize(421, 0))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.548, y1:0.0856364, x2:0.532701, y2:0.955, stop:0.00995025 rgba(227, 255, 113, 255), stop:1 rgba(255, 157, 110, 255));\n"
"font: 10pt \"Cascadia Mono\";")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Stanley)
        QtCore.QMetaObject.connectSlotsByName(Stanley)

    def retranslateUi(self, Stanley):
        _translate = QtCore.QCoreApplication.translate
        Stanley.setWindowTitle(_translate("Stanley", "Dialog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Stanley", "Stanley? Is it really you?"))
        item = self.listWidget.item(2)
        item.setText(_translate("Stanley", "Hurry up and press the button!"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("Stanley", "Button"))
