# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pc\Desktop\gg\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Narrator(object):
    def setupUi(self, Narrator):
        Narrator.setObjectName("Narrator")
        Narrator.resize(476, 356)
        Narrator.setMinimumSize(QtCore.QSize(476, 356))
        Narrator.setMaximumSize(QtCore.QSize(476, 356))
        Narrator.setLayoutDirection(QtCore.Qt.LeftToRight)
        Narrator.setAutoFillBackground(False)
        Narrator.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.393323, y1:0.46, x2:0.911, y2:0.994318, stop:0.00995025 rgba(242, 255, 0, 255), stop:1 rgba(255, 121, 0, 255));")
        self.centralwidget = QtWidgets.QWidget(Narrator)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 63 14pt \"Cascadia Mono\";\n"
"background-color: qlineargradient(spread:pad, x1:0.482925, y1:0, x2:0.538, y2:1, stop:0.00995025 rgba(197, 221, 98, 255), stop:1 rgba(255, 157, 110, 255));")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.548, y1:0.0856364, x2:0.532701, y2:0.955, stop:0.00995025 rgba(227, 255, 113, 255), stop:1 rgba(255, 157, 110, 255));\n"
"font: 10pt \"Cascadia Mono\";")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.548, y1:0.0856364, x2:0.532701, y2:0.955, stop:0.00995025 rgba(227, 255, 113, 255), stop:1 rgba(255, 157, 110, 255));\n"
"font: 10pt \"Cascadia Mono\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.548, y1:0.0856364, x2:0.532701, y2:0.955, stop:0.00995025 rgba(227, 255, 113, 255), stop:1 rgba(255, 157, 110, 255));\n"
"font: 10pt \"Cascadia Mono\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Narrator.setCentralWidget(self.centralwidget)

        self.retranslateUi(Narrator)
        QtCore.QMetaObject.connectSlotsByName(Narrator)

    def retranslateUi(self, Narrator):
        _translate = QtCore.QCoreApplication.translate
        Narrator.setWindowTitle(_translate("Narrator", "MainWindow"))
        self.label.setText(_translate("Narrator", "     Hello! Choose who you are"))
        self.pushButton.setText(_translate("Narrator", "Stanley"))
        self.pushButton_2.setText(_translate("Narrator", "Other person"))
        self.pushButton_3.setText(_translate("Narrator", "Robot"))
