# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pc\Desktop\gg\ans3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Robot(object):
    def setupUi(self, Robot):
        Robot.setObjectName("Robot")
        Robot.resize(612, 551)
        Robot.setMinimumSize(QtCore.QSize(612, 551))
        Robot.setMaximumSize(QtCore.QSize(612, 551))
        Robot.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.393323, y1:0.46, x2:0.911, y2:0.994318, stop:0.00995025 rgba(242, 255, 0, 255), stop:1 rgba(255, 121, 0, 255));")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Robot)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget = QtWidgets.QListWidget(Robot)
        self.listWidget.setStyleSheet("font: 63 14pt \"Cascadia Mono\";\n"
"background-color: qlineargradient(spread:pad, x1:0.482925, y1:0, x2:0.538, y2:1, stop:0.00995025 rgba(197, 221, 98, 255), stop:1 rgba(255, 157, 110, 255));")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_3.addWidget(self.listWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(Robot)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.548, y1:0.0856364, x2:0.532701, y2:0.955, stop:0.00995025 rgba(227, 255, 113, 255), stop:1 rgba(255, 157, 110, 255));\n"
"font: 10pt \"Cascadia Mono\";")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(Robot)
        self.pushButton_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.548, y1:0.0856364, x2:0.532701, y2:0.955, stop:0.00995025 rgba(227, 255, 113, 255), stop:1 rgba(255, 157, 110, 255));\n"
"font: 10pt \"Cascadia Mono\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(Robot)
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.548, y1:0.0856364, x2:0.532701, y2:0.955, stop:0.00995025 rgba(227, 255, 113, 255), stop:1 rgba(255, 157, 110, 255));\n"
"font: 10pt \"Cascadia Mono\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalSlider = QtWidgets.QSlider(Robot)
        self.horizontalSlider.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.548, y1:0.0856364, x2:0.532701, y2:0.955, stop:0.00995025 rgba(227, 255, 113, 255), stop:1 rgba(255, 157, 110, 255));\n"
"font: 10pt \"Cascadia Mono\";")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.horizontalScrollBar = QtWidgets.QScrollBar(Robot)
        self.horizontalScrollBar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.548, y1:0.0856364, x2:0.532701, y2:0.955, stop:0.00995025 rgba(227, 255, 113, 255), stop:1 rgba(255, 157, 110, 255));\n"
"font: 10pt \"Cascadia Mono\";")
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.verticalLayout.addWidget(self.horizontalScrollBar)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.dial = QtWidgets.QDial(Robot)
        self.dial.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.548, y1:0.0856364, x2:0.532701, y2:0.955, stop:0.00995025 rgba(227, 255, 113, 255), stop:1 rgba(255, 157, 110, 255));\n"
"font: 10pt \"Cascadia Mono\";")
        self.dial.setObjectName("dial")
        self.horizontalLayout_2.addWidget(self.dial)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalSlider = QtWidgets.QSlider(Robot)
        self.verticalSlider.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.548, y1:0.0856364, x2:0.532701, y2:0.955, stop:0.00995025 rgba(227, 255, 113, 255), stop:1 rgba(255, 157, 110, 255));\n"
"font: 10pt \"Cascadia Mono\";")
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout_3.addWidget(self.verticalSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.pushButton_4 = QtWidgets.QPushButton(Robot)
        self.pushButton_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.548, y1:0.0856364, x2:0.532701, y2:0.955, stop:0.00995025 rgba(227, 255, 113, 255), stop:1 rgba(255, 157, 110, 255));\n"
"font: 10pt \"Cascadia Mono\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)

        self.retranslateUi(Robot)
        QtCore.QMetaObject.connectSlotsByName(Robot)

    def retranslateUi(self, Robot):
        _translate = QtCore.QCoreApplication.translate
        Robot.setWindowTitle(_translate("Robot", "Dialog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Robot", "Hmm..."))
        item = self.listWidget.item(2)
        item.setText(_translate("Robot", "I really don’t know what to say."))
        item = self.listWidget.item(4)
        item.setText(_translate("Robot", "Well, you can poke the buttons. Or leave."))
        item = self.listWidget.item(6)
        item.setText(_translate("Robot", "Bye, you weird Robot!"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("Robot", "Poke"))
        self.pushButton_3.setText(_translate("Robot", "Poke"))
        self.pushButton_2.setText(_translate("Robot", "Poke"))
        self.pushButton_4.setText(_translate("Robot", "Leave"))

