# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pc\Desktop\gg\last.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1055, 410)
        Dialog.setMinimumSize(QtCore.QSize(1055, 410))
        Dialog.setMaximumSize(QtCore.QSize(1055, 410))
        Dialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.393323, y1:0.46, x2:0.911, y2:0.994318, stop:0.00995025 rgba(242, 255, 0, 255), stop:1 rgba(255, 121, 0, 255));")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setStyleSheet("font: 63 14pt \"Cascadia Mono\";\n"
"background-color: qlineargradient(spread:pad, x1:0.482925, y1:0, x2:0.538, y2:1, stop:0.00995025 rgba(197, 221, 98, 255), stop:1 rgba(255, 157, 110, 255));")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "It\'s really you!"))
        item = self.listWidget.item(2)
        item.setText(_translate("Dialog", "I don’t know why you left the game..."))
        item = self.listWidget.item(4)
        item.setText(_translate("Dialog", "But I made a new one! I’m sure you’ll like it!"))
        item = self.listWidget.item(6)
        item.setText(_translate("Dialog", "I added some cool stuff there! This is a breakthrough in the gaming industry!"))
        item = self.listWidget.item(8)
        item.setText(_translate("Dialog", "So go on, Stanley! On new adventures!"))
        item = self.listWidget.item(10)
        item.setText(_translate("Dialog", "I’m waiting for you in the \"The Stanley Parable: Ultra Deluxe\"!"))
        self.listWidget.setSortingEnabled(__sortingEnabled)

